# Generated by Django 4.2.16 on 2025-05-04 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('libelle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('libelle', models.CharField(max_length=20)),
                ('num_TF', models.CharField(blank=True, max_length=20, null=True)),
                ('titre_foncier', models.FileField(blank=True, null=True, upload_to='titres/')),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='patrimoine.immeuble')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_proprietaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
