# Generated by Django 4.2.16 on 2025-05-04 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patrimoine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='num_TF',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_proprietaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='titre_foncier',
            field=models.FileField(blank=True, null=True, upload_to='titres/'),
        ),
    ]
