# Generated by Django 4.2.16 on 2025-05-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('libelle', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='lotindividuel',
            old_name='lot_individuel',
            new_name='code',
        ),
        migrations.AddField(
            model_name='lotindividuel',
            name='num_TF',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lotindividuel',
            name='titre_foncier',
            field=models.FileField(blank=True, null=True, upload_to='titres/'),
        ),
        migrations.AlterField(
            model_name='lotindividuel',
            name='proprietaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_tiers': 'coproprietaire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_coprop', to='accounts.tiers'),
        ),
        migrations.AlterField(
            model_name='lotindividuel',
            name='immeuble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_immeuble', to='accounts.immeuble'),
        ),
    ]
