# Generated by Django 4.2.16 on 2025-05-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_immeuble_rename_lot_individuel_lotindividuel_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('libelle', models.CharField(max_length=20)),
                ('num_TF', models.CharField(blank=True, max_length=20, null=True)),
                ('titre_foncier', models.FileField(blank=True, null=True, upload_to='titres/')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tier', models.CharField(choices=[('coproprietaire', 'Copropriétaire'), ('immeuble', 'Immeuble'), ('fournisseur', 'Fournisseur')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='lotindividuel',
            name='immeuble',
        ),
        migrations.RemoveField(
            model_name='lotindividuel',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='user',
        ),
    ]
