# Generated by Django 4.2.16 on 2025-05-01 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lot_tier_remove_lotindividuel_immeuble_and_more'),
        ('comptabilite', '0004_alter_abonnement_lot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LotIndividuel',
        ),
        migrations.DeleteModel(
            name='Tiers',
        ),
        migrations.AddField(
            model_name='tier',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='immeuble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='accounts.immeuble'),
        ),
        migrations.AddField(
            model_name='lot',
            name='proprietaire',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('type_tier', 'coproprietaire'), ('type_tier', 'immeuble'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_proprietaire', to='accounts.tier'),
        ),
    ]
