# Generated by Django 4.2.16 on 2025-05-04 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_lotindividuel_delete_tiers_tier_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='immeuble',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir exactement 10 chiffres.', regex='^[0-9]{10}$')]),
        ),
        migrations.DeleteModel(
            name='Immeuble',
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
    ]
