# Generated by Django 4.2.16 on 2024-11-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_compte', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('recette', 'Recette'), ('depense', 'Dépense'), ('ajustement', 'Ajustement')], max_length=50)),
            ],
            options={
                'ordering': ['compte'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type_ecriture', models.CharField(choices=[('DB', 'Débit'), ('CR', 'Crédit')], max_length=2)),
            ],
            options={
                'ordering': ['-transaction__id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_ouvert', models.BooleanField(default=True)),
                ('est_actuel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_operation', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('justif', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('exercice', models.ForeignKey(limit_choices_to={'est_ouvert': True}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='comptabilite.exercicecomptable')),
            ],
            options={
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='SoldeExerciceCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_exercice', to='comptabilite.compte')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_compte', to='comptabilite.exercicecomptable')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exercicecomptable',
            constraint=models.UniqueConstraint(condition=models.Q(('est_actuel', True)), fields=('est_actuel',), name='unique_exercice_actuel'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='comptabilite.compte'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='comptabilite.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='soldeexercicecompte',
            unique_together={('compte', 'exercice')},
        ),
    ]
