# Generated by Django 4.2.16 on 2024-10-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_compte', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('recette', 'Recette'), ('depense', 'Dépense')], max_length=50)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type_ecriture', models.CharField(choices=[('DB', 'Débit'), ('CR', 'Crédit')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_ouvert', models.BooleanField(default=True)),
                ('est_actuel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('libelle', models.CharField(max_length=255)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='comptabilite.exercicecomptable')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exercicecomptable',
            constraint=models.UniqueConstraint(condition=models.Q(('est_actuel', True)), fields=('est_actuel',), name='unique_exercice_actuel'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='comptabilite.compte'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='comptabilite.exercicecomptable'),
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='comptabilite.transaction'),
        ),
    ]
