# Generated by Django 4.2.16 on 2024-10-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compte',
            old_name='numero',
            new_name='compte',
        ),
    ]
