# Generated by Django 4.2.16 on 2025-05-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='exercice',
            field=models.ForeignKey(limit_choices_to={'est_ouvert': True}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_exercice', to='comptabilite.exercicecomptable'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='justif',
            field=models.FileField(blank=True, null=True, upload_to='transactions/'),
        ),
    ]
