# Generated by Django 4.2.16 on 2025-05-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_immeuble_rename_lot_individuel_lotindividuel_code_and_more'),
        ('comptabilite', '0002_alter_transaction_exercice_alter_transaction_justif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant récurrent')),
                ('frequence', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20, verbose_name='Fréquence de facturation')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin (si résiliable)')),
                ('actif', models.BooleanField(default=True, verbose_name='Abonnement actif ?')),
                ('description', models.TextField(blank=True, verbose_name='Détails (ex: charges, services inclus)')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='accounts.lotindividuel', verbose_name='Lot concerné')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
    ]
