# Generated by Django 4.2.16 on 2025-05-05 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_remove_ecriturecomptable_tiers_exclusif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir exactement 10 chiffres.', regex='^[0-9]{10}$')]),
        ),
    ]
