# Generated by Django 4.2.16 on 2024-10-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_rename_numero_compte_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='support',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
