# Generated by Django 4.2.16 on 2024-10-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_transaction_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={'ordering': ['compte']},
        ),
    ]
