# Generated by Django 4.2.16 on 2025-05-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lot_tier_remove_lotindividuel_immeuble_and_more'),
        ('comptabilite', '0003_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='accounts.lot', verbose_name='Lot concerné'),
        ),
    ]
