# Generated by Django 4.2.16 on 2025-05-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_lotindividuel_delete_tiers_tier_user_and_more'),
        ('comptabilite', '0004_alter_abonnement_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='lot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lot'),
        ),
    ]
