# Generated by Django 4.2.16 on 2024-11-03 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_alter_compte_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecriturecomptable',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_operation']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='exercice',
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='libelle',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_operation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
