# Generated by Django 4.2.16 on 2025-05-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0001_initial'),
        ('comptabilite', '0005_alter_abonnement_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='lot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimoine.lot'),
        ),
    ]
