# Generated by Django 4.2.16 on 2024-11-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_alter_ecriturecomptable_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='solde_actuel',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='solde_initial',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='support',
        ),
        migrations.CreateModel(
            name='SoldeExerciceCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_exercice', to='comptabilite.compte')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_compte', to='comptabilite.exercicecomptable')),
            ],
            options={
                'unique_together': {('compte', 'exercice')},
            },
        ),
    ]
