# Generated by Django 4.2.16 on 2024-11-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_remove_compte_solde_actuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='exercice',
            field=models.ForeignKey(limit_choices_to={'est_ouvert': True}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='comptabilite.exercicecomptable'),
        ),
    ]
