# Generated by Django 4.2.16 on 2024-11-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_alter_transaction_exercice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecriturecomptable',
            options={'ordering': ['transaction__id']},
        ),
        migrations.RemoveField(
            model_name='ecriturecomptable',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='justifPdf',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
