# Generated by Django 4.2.16 on 2024-11-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0008_alter_ecriturecomptable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecriturecomptable',
            options={'ordering': ['-transaction__id']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='justifPdf',
        ),
        migrations.AddField(
            model_name='transaction',
            name='justif',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
