# Generated by Django 4.2.16 on 2024-11-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0009_alter_ecriturecomptable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='type_compte',
            field=models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('recette', 'Recette'), ('depense', 'Dépense'), ('ajustement', 'Ajustement')], max_length=50),
        ),
    ]
